default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  host: <%= Rails.application.credentials.db.host %>
  port: <%= Rails.application.credentials.db.port %>
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>

development:
  <<: *default
  database: cas_rip_development

test:
  <<: *default
  database: cas_rip_test

production:
  <<: *default
  database: cas_rip
